### ISSUE TITLE
some issues on data preparation stage

### ISSUE THREAD

**Issue by cxym-yyn** [YangHai-1218/RADet#1]
Hello, author
Thanks for your great work and sharing
I tried to prepare data using ycbv_pbr datastet, but there is an error

usage: collect_image_list.py [-h] [--source-dir SOURCE_DIR]
                             [--save-path SAVE_PATH] [--pattern PATTERN]
collect_image_list.py: error: unrecognized arguments: --image_list /home/ivc2411/path/data/image_lists/train_pbr.txt

Can you give me some advice?

Best

**Comment by YangHai-1218** [comment]
Hi, there is a mistake in readme. And i have fixed it. Please remove the image_list argument for usage.

**Comment by helloyuning** [comment]
thanks for your reply
I have some questions about the paper
1. In the training process, the optimal result is to find the optimal seeds and the distance of the target pixel?
2. In the selection of predicited bboxs, the paper mentions fusing the same category of predicted bboxs to obtain more accurate results. Specifically, by what method is the fusion done. What are the specific differences with nms.

Thanks,
Best

**Comment by helloyuning** [comment]
@YangHai-1218 
Please open the issue!
