### ISSUE TITLE
Performance w.r.t. different occlusion ratios

### ISSUE THREAD

**Issue by ZJU-PLP** [YangHai-1218/RADet#2]
@YangHai-1218 
Hi, hai:
Thanks for sharing so nice work. Could you mind providing the script to get the data of Fig.7 Performance w.r.t. different occlusion ratios in your paper? I cannot find the code to reproduce this work.

**Comment by YangHai-1218** [comment]
Hi, thanks for your interest. 
BOP provides the visib_fract information in scene_gt_info.json. And occlusion_ratio = 1 - visib_fract.
You can use it to draw the figure.

**Comment by ZJU-PLP** [comment]
> Hi, thanks for your interest. BOP provides the visib_fract information in scene_gt_info.json. And occlusion_ratio = 1 - visib_fract. You can use it to draw the figure.

Okkk, thanks for your reply.
