### ISSUE TITLE
some questions about the paper

### ISSUE THREAD

**Issue by helloyuning** [YangHai-1218/RADet#3]
Thanks for your greate work
I have some questions about the paper

1. In the training process, the optimal result is to find the optimal distance between seeds and the target pixel?
2.In the selection of predicited bboxs, the paper mentions fusing the same category of predicted bboxs to obtain more accurate results. Specifically, by what method is the fusion done. What are the specific differences with nms.

Thanks,
Best

**Comment by YangHai-1218** [comment]
Hi, Thanks for your interest.
First, I am not sure the meaning of the optimal distance. But the distance transform is to calculate the minimum distance between the pixel and all the seeds. Second, we use weighted-NMS for fusing the predicted boxes.

**Comment by helloyuning** [comment]
> Hi, Thanks for your interest. First, I am not sure the meaning of the optimal distance. But the distance transform is to calculate the minimum distance between the pixel and all the seeds. Second, we use weighted-NMS for fusing the predicted boxes.

Thank you for your reply, I'm sorry for some problems with my expression.
1. In your paper, you localize the object by calculating the distance between the 2d points of the bbox and the target pixels. How are the 2d points of these target pixels set?
2. can weighted-NMS be interpreted as the basic process is the same as NMS, but the training stage makes the network focus more on high confidence bboxes by changing the training weights of each bboxes.(similar to focoal loss)

**Comment by YangHai-1218** [comment]
First, I still don't understand the true meaning of the question one. The seeds are the pixels of the bounding box border, and we are going to calculate the distance between each pixel and the seeds. If you have more questions, you can check the distance transform method referred in our paper. 
Second, weighted-NMS is only used for inference and has no relationship to training.
