### ISSUE TITLE
combinate it with PFA-Pose

### ISSUE THREAD

**Issue by chenin-wang** [YangHai-1218/RADet#5]
Thanks for your greate work

how you combinate it with PFA-Pose， can you give some advice or code? 
 thanks

**Comment by YangHai-1218** [comment]
Hey, thanks for your interest. PFA-Pose uses WDR-Pose for pose initialization. To combine RADet with PFA-Pose, we run WDR-Pose on the cropped patch according to the detected bounding box by RADet.

**Comment by chenin-wang** [comment]
thanks for your reply
If I want to combine RADet with PFA-Pose, do I have to use WDR-pose? Is that what you mean?

in this paper chapter 4.2，you mention "The original PFA-Pose cannot handle multiple instances from the same class, making it inapplicable to some datasets. So we only reproduce its results on LM-O and YCB. "
you combine RADet with PFA-Pose.

in the nest paragraph, "To demonstrate its generalization ability, we test our detection method
on YCB with two other typical pose regression networks,WDR-Pose [19] and CDPNv2 [26]. Table 6 provides the
results, evidencing that our detection method consistently improves the pose results" ,
you combine RADet with WDR-Pose，too.

Aren't the PFA-Pose and WDR-Pose independent?

**Comment by YangHai-1218** [comment]
No, for the above one you mentioned, PFA-Pose is combined with the original WDR-Pose which can not handle multiple instances. If we combine RADet with WDR-Pose(PFA-Pose), RADet can handle the case with multiple instances.

**Comment by chenin-wang** [comment]
Thank you so much.
 i want to re-implement RADet with the PFA-Pose.  but there is no demo combined RADet with the PFA-Pose in your git repository.
I found the open source link of the PFA-Pose，https://github.com/cvlab-epfl/perspective-flow-aggregation , In your paper, you mentioned that bbox needs to be passed to the PFA-Pose. Is there any other information that needs to be passed? Do I need to make a lot of modifications to the code of the PFA-Pose to adapt to RADet?

**Comment by YangHai-1218** [comment]
No. We only re-implement WDR-Pose to intergerate it into PFA-Pose pipeline and keep the PFA-Pose refinement module. In the future, we will open-source the re-implemented WDR-Pose. But you can also try to re-implement it by yourself. Basically, you need to first crop the patch according to the detected bbox and resize to a fixed resolution. And WDR-Pose should be re-trained in this new setting.

**Comment by chenin-wang** [comment]
thanks for your reply. maybe give it a try.

**Comment by YangHai-1218** [comment]
Hey, in our latest work [Pseudo Flow Consistency for Self-Supervised 6D Object Pose Estimation](https://arxiv.org/abs/2308.10016),  we combine WDR-Pose with RADet for pose initialization. We will open source the re-implemented WDR-Pose in [this code repo](https://github.com/YangHai-1218/PseudoFlow) in next few days, please stay tuned.

**Comment by YangHai-1218** [comment]
We have released the code for combining RADet with WDR-Pose [here](https://github.com/YangHai-1218/PseudoFlow). Please check!

**Comment by chenin-wang** [comment]
nice!
