### ISSUE TITLE
Where to download COCO background images for the RandomBackground augmentation step?

### ISSUE THREAD

**Issue by jfitzg7** [YangHai-1218/RADet#8]
Hey @YangHai-1218,

I ran into an issue with the RandomBackground augmentation step specified in `configs/base/datasets/bop_detection.py`, which appears to be looking for background images in the `data/coco` directory by default. Just by looking at the code it seems like you could potentially use any set of images as the background. But just for the sake of it, do you guys know exactly which images you used and where to download them?

Also for the time being, I've just commented out the RandomBackground augmentation step in the `configs/base/datasets/bop_detection.py` file, would that be acceptable? Or is this a crucial augmentation step?

**Comment by YangHai-1218** [comment]
Hey, sorry for the delay. You can comment this step if you don't have COCO dataset. In my oppion, it's better to use this step for better generalization. You can accesss these images by downloading `COCO train 2017` dataset

**Comment by jfitzg7** [comment]
No worries, thank you @YangHai-1218!
